ulyssa/modalkit

.github/workflows/ci.yml, Cargo.toml, README.md
The newer ratatui from #120 requires at least Rust 1.67. I'm going to bump the MSRV. (I already did this for iamb in ulyssa/iamb#164.)
=> Update minimum Rust version to 1.67

src/editing/key.rs, src/env/emacs/keybindings.rs, src/env/mixed.rs, src/env/mod.rs, src/env/vim/keybindings.rs, src/input/bindings.rs, src/input/mod.rs
Currently, when an input sequence is unmapped, `ModeKeys::unmapped` gets called on just the last key in the sequence. This isn't the right behaviour, and makes it so that doing the common Insert mode mapping of "jj" or "jk" can't work right, since typing an unmapped sequence like "jo" will only type the "o" character. Instead, when a sequence is unmapped, `ModeKeys::unmapped` should be called on the _first_ character, and then the rest of the sequence should be retries. That way, if "jk" is mapped to "<Esc>", typing "jjk" will type "j" and then go to Normal mode.
=> Retry suffix of unmapped key sequences

Cargo.toml, src/editing/base.rs, src/editing/completion.rs, src/editing/cursor/mod.rs, src/editing/cursor/state.rs, src/editing/rope/mod.rs, src/env/emacs/keybindings.rs, src/env/mod.rs, src/env/vim/keybindings.rs, src/widgets/list.rs, src/widgets/windows/mod.rs
The MSRV is still 1.67, but this should keep it easy to work with newer Rust toolchains locally.
=> Fix Clippy 1.75 warnings

crates/modalkit/Cargo.toml
CI broke on #131 because a change in `arboard@3.3.1` doesn't compile on Windows. Hopefully it's the only issue, and going back to `arboard@3.3.0` works.
=> Use exactly arboard@3.3.0 for now

crates/modalkit/src/env/vim/command/mod.rs
I had removed these in #125, because I was thinking that I didn't want to allow comparisons against the context, but this actually makes it hard to embed it into other things that need to derive `Eq`/`PartialEq` in `iamb`, so I'm adding it back.
=> Add Eq and PartialEq back to CommandContext

crates/modalkit/src/editing/action.rs, crates/modalkit/src/editing/key.rs
This adds a `MacroAction` variant that fetches the macro from the `String` argument instead of looking up the macro from the specified register. This should make it easier to implement simple keybindings that map to a series of kepresses in iamb for now.
=> Add MacroAction::Run variant to make custom keybindings easier

crates/modalkit/src/editing/key.rs, crates/modalkit/src/key/mod.rs
While looking at using `MacroAction::Run` to implement custom keybindings in iamb, I realized that there should be something that prevents getting caught executing a macro without human input forever. For now, I've just made this 100, but I can make it adjustable in the future if it ever comes up.
=> Limit recursive macros

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/modalkit-ratatui/Cargo.toml, crates/modalkit-ratatui/src/lib.rs, crates/modalkit-ratatui/src/list.rs, crates/modalkit-ratatui/src/screen.rs
Hi! Thanks for the incredible crate. The amount of time I've saved in building a familiar TUI experience with this is astounding.
Ratatui 0.26 has a few niceties like the flex layout modes and a number of bugfixes, so I've bumped modalkit-ratatui and fixed the tiny amount of breaking changes that affect modalkit.
I realise that the primary consumer of modalkit (`iamb`?) will still be pinned to ratatui 0.23 so I'm happy to do the version bump there too and see what comes out of it if you think this ratatui update is worthwhile.
Tests all look good and the behaviour of the example seems identical before/after updating to my untrained eye.
=> Update modalkit-ratatui to ratatui 0.26

crates/modalkit-ratatui/examples/editor.rs, crates/modalkit/src/env/emacs/keybindings.rs, crates/modalkit/src/env/keyparse.rs, crates/modalkit/src/env/vim/keybindings.rs, crates/modalkit/src/key/mod.rs, crates/modalkit/src/key/parse.rs
I enabled the Kitty keyboard enhancements in ulyssa/iamb#272, but this broke using some keybindings like `<C-I>` and `<C-[>` since they no longer get sent as `<Tab>` and `<Esc>` respectively. These (and similar) should have duplicate entries in the Vim and Emacs keybindings so that enabling improved keypresses doesn't break using them. The key parsing code should also stop pretending that these are always the same keys, since people could reasonable want to set up custom mappings for one but not the other when using a terminal that supports sending the `CSI u` sequences.
There is a little bit of trickiness here: the crossterm representation for some keypresses like Alt+Shift+J sometimes uses `j` (Kitty keyboard enhancement protocol) and sometimes uses `J` (non-enhanced). I've tried to …
=> Add duplicate bindings for terminals that support enhanced keys

Cargo.lock, crates/modalkit/Cargo.toml, crates/modalkit/src/editing/store/register.rs
Someone pointed out in `#iamb-users:0x.badd.cafe` a couple weeks ago that the Wayland clipboard was inaccessible with `"*` and `"+`. `arboard` needs an explicit feature passed to it to support it. I've enabled it, and also added a `clipboard` feature to the `modalkit` crate to allow controlling whether `arboard` gets pulled in at all.
=> Enable Wayland clipboard support and make arboard optional

crates/modalkit-ratatui/examples/editor.rs, crates/modalkit-ratatui/src/cmdbar.rs, crates/modalkit-ratatui/src/list.rs, crates/modalkit-ratatui/src/screen.rs, crates/modalkit/src/actions.rs, crates/modalkit/src/editing/application.rs, crates/modalkit/src/editing/buffer/mod.rs, crates/modalkit/src/editing/buffer/selection.rs, crates/modalkit/src/editing/rope/mod.rs, crates/modalkit/src/editing/store/mod.rs, crates/modalkit/src/editing/store/register.rs, crates/modalkit/src/env/emacs/keybindings.rs, crates/modalkit/src/env/vim/keybindings.rs, crates/modalkit/src/env/vim/mod.rs, crates/modalkit/src/prelude.rs, crates/scansion/src/editor.rs, crates/scansion/src/lib.rs
In addition to jumping through a buffer to matching regular expressions, Kakoune can perform other actions that all use the same search regex history and interact with the same register (see #62 and #63 for example).
In order to support these, focusing the command bar should specify the action to take when submitting its contents. I've replaced `Register::LastSearch` (`"/`) and `Register::LastCommand` (`":`) with a `Register::LastCommand(CommandType)` variant. History for their contents has also moved into the `RegisterStore`, and is done in a way that should make #69, #130, and any other new command bar types very straightforward to implement.
=> Keybindings should provide Action to command bar

Cargo.lock, crates/modalkit-ratatui/Cargo.toml, crates/modalkit-ratatui/src/screen.rs, crates/modalkit-ratatui/src/windows/layout.rs, crates/modalkit-ratatui/src/windows/mod.rs, crates/modalkit-ratatui/tests/window-layout.json
Hi,
This PR is to support restoring layouts with with zoom and focus.
Related issues:
- https://github.com/ulyssa/iamb/issues/247
- https://github.com/ulyssa/iamb/issues/250
A new struct `WindowLayoutStorage` has been created to store: the windows layout, which window is in focus, and if the focused window is zoomed. 
`TabLayoutDescription` has been updated to hold this struct in place of `WindowLayoutStorage` as well as store the currently selected tab.
I am not set on the name `WindowLayoutStorage`; would you be open to naming it `TabLayoutDescription`, and rename `TablayoutDescription` to `AppLayoutDescription` or something similar?
This seems more logical to me as currently `TabLayoutDescription` does not hold the layout of a tab, but rather the layout of the top level application. …
=> Save zoom and focused window from layout so that it can be restored

crates/modalkit-ratatui/src/cmdbar.rs, crates/modalkit-ratatui/src/screen.rs, crates/modalkit-ratatui/src/textbox.rs, crates/modalkit-ratatui/src/windows/layout.rs
These options are to help support ulyssa/iamb#128 by making it possible for applications specify how to style more of the parts within the `modalkit-ratatui` widgets.
=> Improve widget styling options in modalkit-ratatui

crates/modalkit-ratatui/src/textbox.rs, crates/modalkit/src/editing/buffer/mod.rs, crates/modalkit/src/editing/context.rs, crates/modalkit/src/editing/key.rs, crates/modalkit/src/editing/rope/mod.rs, crates/modalkit/src/env/vim/keybindings.rs
While looking into ulyssa/iamb#297, I think I've convinced myself that the default that `EditContext`/`EditContextBuilder` uses for `last_column` is wrong and a potential footgun that results in accidentally misusing `InsertTextAction` and others outside of a keybinding context. It should default to `true` so that building `Action` values from scratch don't unexpectedly clamp the cursor, but require explicitly requesting that behaviour via the builder interface.
=> Change default for `last_column` in `EditContext`

crates/modalkit-ratatui/src/windows/layout.rs
This fixes the issue observed in ulyssa/iamb#307 where typing `<C-W>o` after restoring the window layout could reproducibly crash. The problem is that when the `ResizeInfo` contains window lengths (which it always does on restore, since they get snapshotted), they don't get cleared when `WindowLayoutState::only` is called. This results in an inconsistent state that the assertion in `set_area_lens` runs into later on.
=> Clear resize info when closing all but one window

crates/modalkit-ratatui/src/windows/layout.rs, crates/modalkit-ratatui/src/windows/tree.rs, crates/modalkit/src/editing/buffer/mod.rs, crates/modalkit/src/editing/rope/diff.rs, crates/modalkit/src/editing/rope/mod.rs, crates/modalkit/src/editing/store/cursor.rs, crates/modalkit/src/key/mod.rs
This PR fixes the new lints and warnings from Clippy 1.80.
=> Fix Clippy 1.80 warnings

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/modalkit-ratatui/Cargo.toml, crates/modalkit-ratatui/examples/editor.rs, crates/modalkit-ratatui/src/lib.rs
just a quick fix bringing this up-to-date with the upstream `ratatui` crate.
i mostly wanted this change for compatibility with events
=> Update `crossterm` and `ratatui` dependencies and bump MSRV to 1.74

Cargo.lock, crates/modalkit-ratatui/Cargo.toml, crates/modalkit-ratatui/src/textbox.rs
Respect unicode width
- https://github.com/ulyssa/iamb/issues/293 
- https://github.com/ulyssa/iamb/pull/358
=> Use Unicode column width when calculating terminal cursor offset

crates/scansion/examples/read-loop.rs
Adds a compile-able example for `scansion`, based on the sample code already present in a header comment:
* Extracted as a runnable example (i.e., `cargo run --example read-loop`).
* Extended to support emacs or vi mode, similar to the other example present in this repo.
=> Build basic scansion loop example

.github/workflows/ci.yml, Cargo.toml, crates/keybindings/Cargo.toml, crates/keybindings/src/lib.rs, crates/modalkit-ratatui/Cargo.toml, crates/modalkit/Cargo.toml, crates/modalkit/src/editing/cursor/choice.rs, crates/modalkit/src/editing/key.rs, crates/scansion/examples/read-loop.rs, rust-toolchain.toml
This adds a shared Clippy config, and updates it to allow a couple of the more pedantic lints.
=> Make workspace share Clippy configuration

Cargo.lock, crates/modalkit-ratatui/Cargo.toml, crates/modalkit/Cargo.toml
This updates `modalkit-ratatui` to work with `ratatui@0.29.0` which is currently the most recent release.
=> Update `ratatui` dependency to `0.29.0`

crates/editor-types-macros/src/lib.rs, crates/editor-types-parser/src/lib.rs, crates/editor-types/src/lib.rs, crates/editor-types/src/prelude.rs
This adds a `jump` keyword to the `action!` macro so that `Action::Jump` can be produced.
=> Add support for `Action::Jump` to `action!` macro

crates/modalkit-ratatui/src/list.rs
This addresses the concern in https://github.com/ulyssa/iamb/pull/404#issuecomment-2905038078
=> Allow consumers to customize list searching to not rely on `to_string`

crates/modalkit/src/editing/completion.rs, crates/modalkit/src/util.rs
Since the `Store` contains a `Box<dyn Completer<I>>`, this type should really always be `Send` and `Sync` so that the `Store` will always play nicely with multithreaded programs (like iamb).
=> Implementations of `Completer` should be `Send` and `Sync`

crates/modalkit/src/env/vim/keybindings.rs
This fixes #175 , which is caused by running `SetInsertStyle` twice in the sequence of keypresses (on the first `c`, and again on the second `c`). It should be using the `edit_range_end!` macro instead of `change_range!`, so that it takes into account the behaviour of the first `c`, which already sets the context's `EditAction` and `InsertStyle`.
=> Fix implementation of `cc` keybinding
